<a href="https://colab.research.google.com/github/kvneswar/PythonForDSAndMLBootcamp/blob/main/03_numpy_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

*   NumPy is a Linear Algebra Library in Python
*   Almost all the libraries in PyData are rely on NumPy as one or their building blocks.
*It is incredibly fast, as it has binding to C libraries
# * To install NumPy -> **conda install numpy** or **pip install numpy**


*   NumPy arrays comes in 2 falvors i.e. vectors and matrices
*   vectors are 1 dimentional and matrices are 2D (or it can have one row or one column)



    



In [ ]:
import numpy as np

In [ ]:
arr = np.array([1, 2, 3])

arr #for the type

array([1, 2, 3])

In [ ]:
print(arr)

my_mat = np.array([[1, 2], [3, 4]])

my_mat

[1 2 3]


array([[1, 2],
       [3, 4]])

In [ ]:
print(np.arange(0, 10)) #similar to range function in list
print(np.arange(0, 10, 4)) #to skip

print(np.zeros((2, 3)))

print(np.eye(4))

[0 1 2 3 4 5 6 7 8 9]
[0 4 8]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
print(np.random.rand())
print(np.random.rand(5))
print(np.random.rand(5, 5))
print(np.random.randn(5))
print(np.random.randn(5, 5))

print(np.random.randint(10))
print(np.random.randint(0, 20, 5)) # 5 random integers b/w 0-20

0.7792110036011262
[0.70275356 0.79213705 0.91800178 0.26049419 0.64345346]
[[0.45103425 0.05144747 0.41962183 0.02921816 0.4421643 ]
 [0.75756085 0.80100231 0.21450052 0.62352538 0.56604142]
 [0.11035255 0.07177668 0.91685418 0.97158829 0.9450414 ]
 [0.03721262 0.70463355 0.503701   0.95746268 0.9931466 ]
 [0.37219409 0.27626489 0.62775797 0.27127616 0.49469966]]
[-1.0701014   1.39625297 -0.0310707   0.28366732  0.81587908]
[[ 0.67384022  0.60616554  1.38277825  0.09706521  0.84345084]
 [ 1.13929734  0.50465094  0.34070484 -0.25558744  0.5847857 ]
 [ 0.62292648 -0.67835936 -0.42960241  1.14618313 -1.14501254]
 [-0.26981658  0.31273704  0.64009876 -0.16081863  0.11428551]
 [-1.01473     0.09042117 -1.21461408 -1.64860055 -1.16465256]]
0
[ 5 15 18  9  5]


In [ ]:
new_array = np.random.randint(0, 100, 5)

print(new_array)
print(new_array.max())
print(new_array.argmax()) #max element location
print(new_array.min())
print(new_array.argmin()) #min element location

print(new_array.shape) #returns the array dimension
print(new_array.dtype) #data type of the array


[33 11 46 60 42]
60
3
11
1
(5,)
int64


In [ ]:
from numpy.random import randint #like the static import

print(randint(0, 100, 10))

[57  6 44 44 34 17 63 47  5 79]


# NUMPY INDEXING

In [32]:
arr = np.arange(0, 10)

print(arr)

print(arr[0:4])
print(arr[:-4])
print(arr[5:])

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3]
[0 1 2 3 4 5]
[5 6 7 8 9]


# PASS BY REFERENCE

In [38]:
arr = np.arange(0, 10)

print(arr)

arr_partial = arr[5:]

arr_partial[:] = 100 #original reference also getting updated

print(arr_partial)
print(arr)

arr = np.arange(0, 10)

arr_copy = arr.copy()

arr_partial = arr_copy[5:]
arr_partial[:] = 100        #original arr didn't get changed

print(arr)
print(arr_partial)
print(arr_copy)

[0 1 2 3 4 5 6 7 8 9]
[100 100 100 100 100]
[  0   1   2   3   4 100 100 100 100 100]
[0 1 2 3 4 5 6 7 8 9]
[100 100 100 100 100]
[  0   1   2   3   4 100 100 100 100 100]
