<a href="https://colab.research.google.com/github/kvneswar/PythonForDSAndMLBootcamp/blob/main/03_numpy_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

*   NumPy is a Linear Algebra Library in Python
*   Almost all the libraries in PyData are rely on NumPy as one or their building blocks.
*It is incredibly fast, as it has binding to C libraries
# * To install NumPy -> **conda install numpy** or **pip install numpy**


*   NumPy arrays comes in 2 falvors i.e. vectors and matrices
*   vectors are 1 dimentional and matrices are 2D (or it can have one row or one column)



    



In [1]:
import numpy as np

In [8]:
arr = np.array([1, 2, 3])

arr #for the type

array([1, 2, 3])

In [11]:
print(arr)

my_mat = np.array([[1, 2], [3, 4]])

my_mat

[1 2 3]


array([[1, 2],
       [3, 4]])

In [25]:
print(np.arange(0, 10)) #similar to range function in list
print(np.arange(0, 10, 4)) #to skip

print(np.zeros((2, 3)))

print(np.eye(4))

[0 1 2 3 4 5 6 7 8 9]
[0 4 8]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
