<a href="https://colab.research.google.com/github/kvneswar/PythonForDSAndMLBootcamp/blob/main/03_numpy_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

*   NumPy is a Linear Algebra Library in Python
*   Almost all the libraries in PyData are rely on NumPy as one or their building blocks.
*It is incredibly fast, as it has binding to C libraries
# * To install NumPy -> **conda install numpy** or **pip install numpy**


*   NumPy arrays comes in 2 falvors i.e. vectors and matrices
*   vectors are 1 dimentional and matrices are 2D (or it can have one row or one column)



    



In [1]:
import numpy as np

In [ ]:
arr = np.array([1, 2, 3])

arr #for the type

array([1, 2, 3])

In [ ]:
print(arr)

my_mat = np.array([[1, 2], [3, 4]])

my_mat

[1 2 3]


array([[1, 2],
       [3, 4]])

In [ ]:
print(np.arange(0, 10)) #similar to range function in list
print(np.arange(0, 10, 4)) #to skip

print(np.zeros((2, 3)))

print(np.eye(4))

[0 1 2 3 4 5 6 7 8 9]
[0 4 8]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
print(np.random.rand())
print(np.random.rand(5))
print(np.random.rand(5, 5))
print(np.random.randn(5))
print(np.random.randn(5, 5))

print(np.random.randint(10))
print(np.random.randint(0, 20, 5)) # 5 random integers b/w 0-20

0.7792110036011262
[0.70275356 0.79213705 0.91800178 0.26049419 0.64345346]
[[0.45103425 0.05144747 0.41962183 0.02921816 0.4421643 ]
 [0.75756085 0.80100231 0.21450052 0.62352538 0.56604142]
 [0.11035255 0.07177668 0.91685418 0.97158829 0.9450414 ]
 [0.03721262 0.70463355 0.503701   0.95746268 0.9931466 ]
 [0.37219409 0.27626489 0.62775797 0.27127616 0.49469966]]
[-1.0701014   1.39625297 -0.0310707   0.28366732  0.81587908]
[[ 0.67384022  0.60616554  1.38277825  0.09706521  0.84345084]
 [ 1.13929734  0.50465094  0.34070484 -0.25558744  0.5847857 ]
 [ 0.62292648 -0.67835936 -0.42960241  1.14618313 -1.14501254]
 [-0.26981658  0.31273704  0.64009876 -0.16081863  0.11428551]
 [-1.01473     0.09042117 -1.21461408 -1.64860055 -1.16465256]]
0
[ 5 15 18  9  5]


In [ ]:
new_array = np.random.randint(0, 100, 5)

print(new_array)
print(new_array.max())
print(new_array.argmax()) #max element location
print(new_array.min())
print(new_array.argmin()) #min element location

print(new_array.shape) #returns the array dimension
print(new_array.dtype) #data type of the array


[33 11 46 60 42]
60
3
11
1
(5,)
int64


In [ ]:
from numpy.random import randint #like the static import

print(randint(0, 100, 10))

[57  6 44 44 34 17 63 47  5 79]


# NUMPY INDEXING

In [ ]:
arr = np.arange(0, 10)

print(arr)

print(arr[0:4])
print(arr[:-4])
print(arr[5:])

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3]
[0 1 2 3 4 5]
[5 6 7 8 9]


# PASS BY REFERENCE

In [ ]:
arr = np.arange(0, 10)

print(arr)

arr_partial = arr[5:]

arr_partial[:] = 100 #original reference also getting updated

print(arr_partial)
print(arr)

arr = np.arange(0, 10)

arr_copy = arr.copy()

arr_partial = arr_copy[5:]
arr_partial[:] = 100        #original arr didn't get changed

print(arr)
print(arr_partial)
print(arr_copy)

[0 1 2 3 4 5 6 7 8 9]
[100 100 100 100 100]
[  0   1   2   3   4 100 100 100 100 100]
[0 1 2 3 4 5 6 7 8 9]
[100 100 100 100 100]
[  0   1   2   3   4 100 100 100 100 100]


In [4]:
#2D ARRAY

arr_2d = np.array([[5, 10, 15], 
          [20, 25, 30], 
          [30, 35, 40]])

print(arr_2d)

print(arr_2d[0])

print(arr_2d[0][0]) 
print(arr_2d[0, 0]) #both are the same

#to get the top right corner
print(arr_2d[:2, 1:])


[[ 5 10 15]
 [20 25 30]
 [30 35 40]]
[ 5 10 15]
5
5
[[10 15]
 [25 30]]


In [10]:
#CONDITIONAL SELECTION

arr = np.arange(0, 11)

print(arr)

bool_arr = arr > 5

print(bool_arr)

print(arr[bool_arr])

print(arr[arr<3])


[ 0  1  2  3  4  5  6  7  8  9 10]
[False False False False False False  True  True  True  True  True]
[ 6  7  8  9 10]
[0 1 2]


In [11]:
print(np.arange(50).reshape(5, 10))

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]


In [19]:
#NUMPY OPERATIONS

arr = np.arange(1, 10)

print(arr)

print(arr + arr)
print(arr - arr)
print(arr * arr)
print(arr / arr)
print(arr + 100)
print(np.sqrt(arr))
print(np.sin(arr))
print(np.log(arr))

#ADDITIONAL FUNCTIONS https://docs.scipy.org/doc/numpy-1.10.1/reference/ufuncs.html

[1 2 3 4 5 6 7 8 9]
[ 2  4  6  8 10 12 14 16 18]
[0 0 0 0 0 0 0 0 0]
[ 1  4  9 16 25 36 49 64 81]
[1. 1. 1. 1. 1. 1. 1. 1. 1.]
[101 102 103 104 105 106 107 108 109]
[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.        ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825  0.41211849]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]
